service: hyuns-api
frameworkVersion: '2'

custom:
  env: ${file(./env/${opt:stage, 'dev'}.json)}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20211216
  region: ap-northeast-2
  stage: dev
  environment:
    DB_CONNECT: ${self:custom.env.DB_CONNECT}
    MASTER_PASSWORD: ${self:custom.env.MASTER_PASSWORD}

functions:
  authLogin:
    handler: src/auth.login
    events: 
      - http:
          path: auth/login
          method: post

  authCreateAccount:
    handler: src/auth.createAccount
    events: 
      - http:
          path: auth/account
          method: post

  authDeleteAccount:
    handler: src/auth.deleteAccount
    events: 
      - http:
          path: auth/account
          method: delete

  authPatchAccount:
    handler: src/auth.patchAccount
    events: 
      - http:
          path: auth/account
          method: patch
