service: hyuns-api
frameworkVersion: '2'

custom:
  env: ${file(./env/${opt:stage, 'dev'}.json)}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20211216
  region: ap-northeast-2
  stage: dev
  environment:
    DB_CONNECT: ${self:custom.env.DB_CONNECT}
    MASTER_PASSWORD: ${self:custom.env.MASTER_PASSWORD}

functions:
  authLogin:
    handler: src/auth.login
    events: 
      - http:
          path: auth/login
          method: post

  authCreateAccount:
    handler: src/auth.createAccount
    events: 
      - http:
          path: auth/account
          method: post

  authDeleteAccount:
    handler: src/auth.deleteAccount
    events: 
      - http:
          path: auth/account
          method: delete

  authPatchAccount:
    handler: src/auth.patchAccount
    events: 
      - http:
          path: auth/account
          method: patch

  serverCreate:
    handler: src/server.serverCreate
    events: 
      - http:
          path: server
          method: post

  serversInfo:
    handler: src/server.serversInfo
    events: 
      - http:
          path: server/info
          method: get

  serverInfo:
    handler: src/server.serverInfo
    events: 
      - http:
          path: server/info/{serverName}
          method: get

  serverSendMessage:
    handler: src/server.serverSendMessage
    events: 
      - http:
          path: server/message/{serverName}
          method: post

  serversMessageList:
    handler: src/server.serversMessageList
    events: 
      - http:
          path: server/message
          method: get

  serverMessageList:
    handler: src/server.serverMessageList
    events: 
      - http:
          path: server/message/{serverName}
          method: get

  serverPatch:
    handler: src/server.serverPatch
    events: 
      - http:
          path: server/{serverName}
          method: patch

  serverRemove:
    handler: src/server.serverRemove
    events: 
      - http:
          path: server/{serverName}
          method: delete

  serverMessageRemove:
    handler: src/server.serverMessageRemove
    events: 
      - http:
          path: server/message/{messageId}
          method: delete